<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.9" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.9" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.9" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Skat.KawkaProject.Kafka\Skat.KawkaProject.Kafka.csproj" />
        <ProjectReference Include="..\Skat.KawkaProject.Features.Connections\Skat.KawkaProject.Features.Connections.csproj" />
    </ItemGroup>
</Project>
